### ISSUE TITLE
About the figure2 in the paper

### ISSUE THREAD

**Issue by lwmming** [zhipeng-wei/Image-to-Video-I2V-attack#1]
Hi, Zhipeng. It is a insightful work! It is my pleasure to consult you on the computing of cos-similarity in Figure2 in paper. According your advice, for a video(dimension: [1,3,32,224,224]), I choose the the intermediate features extracted from the first 3D-Resnet block of NL-101. Its dimension is [512,4,28,28]. Besides, I extracte the activation from ResNet101 for this video. Its dimension is [32,512,28,28]. How to compute the cos similarity for them? Look forward to you reply.

**Comment by zhipeng-wei** [comment]
Thanks for your attention. It's great to see you again !
I use torch.nn.functional.interpolate to resize the temporal dimension of image features, thus image features match video features.

**Comment by lwmming** [comment]
I just want to make sure. Is that "[32,512,28,28]  resize to [4,512,28,28]"?

**Comment by zhipeng-wei** [comment]
Yes!

**Comment by lwmming** [comment]
Thank you very much~
