### ISSUE TITLE
About the equation of ASR

### ISSUE THREAD

**Issue by Sammy42779** [zhipeng-wei/Image-to-Video-I2V-attack#2]
Hi, how do you calculate the ASR, and does this relate to the top-1 performance somehow?
Look forward to your reply. 
Thanks!

**Comment by zhipeng-wei** [comment]
Hi, top-1 performace is evaluated on the validation datasets of UCF-101 or Kinetics-400. While ASR is evaluated on randomly sampled dataset, where each sample is correctly classified by all models. For examples, we sample 400 videos from Kinetics-400, where 230 videos are misclassified by one black-box models, thus its ASR is 230/400.
