### ISSUE TITLE
About the necessity of I2V

### ISSUE THREAD

**Issue by lwmming** [zhipeng-wei/Image-to-Video-I2V-attack#3]
Hi, Zhipeng. I'm confused about the necessity of using image models to attack video models. For black-box video attack, why would you use an image model as the substitute model instead of directly using a video model? Could you help me with this confusion? Thank you very much~

**Comment by zhipeng-wei** [comment]
Hi, lwmming. We consider the case that videos are more difficult to collect than images. Hence, using image models as the substitute model can simply the attack process. In addition, Fig 6 in our paper demonstrates that ENS-I2V can achieve better results than using a video model as the white-box substitute model even without the label information. Besides, we illustrate that cross-modal transferability between images and videos exists. 
I hope this can help you. ^-^

**Comment by lwmming** [comment]
Very gelivable！ thank you so much~
