### ISSUE TITLE
导入包gluoncv.torch.data的问题

### ISSUE THREAD

**Issue by xiaopengge2000** [zhipeng-wei/Image-to-Video-I2V-attack#6]
您在进行数据处理的时候使用了
from gluoncv.torch.data  import video_transforms, volume_transforms, multiGridHelper, MultiGridBatchSampler。
我在复现您的代码时，发现无法导入该方法。我尝试将gluoncv更新到与您一致的版本，但是该问题仍未得到解决。希望得到您的回复。
![image](https://github.com/zhipeng-wei/Image-to-Video-I2V-attack/assets/132648259/de529b64-8afd-401d-aa67-d7bb0c9e1a27)

**Comment by zhipeng-wei** [comment]
The following code is my [gluoncv env path]/torch/data/\_\_init__.py 
```python
from .video_cls.dataset_classification import VideoClsDataset
from .video_cls.dataset_classification import build_dataloader, build_dataloader_test
from .video_cls.multigrid_helper import multiGridHelper, MultiGridBatchSampler
from .coot.dataloader import create_datasets, create_loaders
from . import registry
from .transforms.videotransforms import video_transforms, volume_transforms
``` 
Maybe you should copy the last line into your \_\_init__.py  file.
Hope this comment could solve your question.

**Comment by xiaopengge2000** [comment]
根据您给的方法，已经成功解决了。谢谢
